export const CONTROL_SERVER_PORT = Number(process.env.CONTROL_SERVER_PORT || 2099)
export const HERMES_API_SERVER_PORT = Number(process.env.HERMES_API_SERVER_PORT || 8742)
export const HERMES_API_SERVER_HOST = String(process.env.HERMES_API_SERVER_HOST || '127.0.0.1')
export const HERMES_API_SERVER_BASE_URL = String(
  process.env.HERMES_API_SERVER_BASE_URL || `http://${HERMES_API_SERVER_HOST}:${HERMES_API_SERVER_PORT}/v1`
).replace(/\/$/, '')
export const HERMES_CHAT_REQUEST_TIMEOUT_MS = 500000
export const HERMES_REASONING_TASK_LEASE_MS = Number(process.env.HERMES_REASONING_TASK_LEASE_MS || 120000)
export const HERMES_REASONING_TASK_HARD_TIMEOUT_MS = Number(process.env.HERMES_REASONING_TASK_HARD_TIMEOUT_MS || 1500000)
export const HERMES_REASONING_TASK_MAX_RENEWS = Number(
  process.env.HERMES_REASONING_TASK_MAX_RENEWS
  || Math.max(2, Math.ceil(HERMES_REASONING_TASK_HARD_TIMEOUT_MS / HERMES_REASONING_TASK_LEASE_MS) - 1)
)
export const HERMES_REASONING_MIN_ACCEPT_SCORE = 80
export const HERMES_REASONING_MAX_QUALITY_RETRIES = 2
export const HERMES_REASONING_PROVIDER_PROBE_TIMEOUT_MS = Number(process.env.HERMES_REASONING_PROVIDER_PROBE_TIMEOUT_MS || 12000)
export const HERMES_REASONING_TRANSIENT_PROBE_FAILURE_BUDGET = Number(process.env.HERMES_REASONING_TRANSIENT_PROBE_FAILURE_BUDGET || 3)