export function createChatService(deps) {
  return {
    HERMES_API_SERVER_BASE_URL: deps.HERMES_API_SERVER_BASE_URL,
    HERMES_CHAT_REQUEST_TIMEOUT_MS: deps.HERMES_CHAT_REQUEST_TIMEOUT_MS,
    appendHermesLog: deps.appendHermesLog,
    buildActiveHermesChatRequestPayload: deps.buildActiveHermesChatRequestPayload,
    buildChatContextSourcesPayload: deps.buildChatContextSourcesPayload,
    buildHermesBinding: deps.buildHermesBinding,
    buildHermesChatMessages: deps.buildHermesChatMessages,
    buildHermesOutboundRequestSummary: deps.buildHermesOutboundRequestSummary,
    getActiveHermesChatRecovery: deps.getActiveHermesChatRecovery,
    getActiveHermesChatRequest: deps.getActiveHermesChatRequest,
    getHermesChatFilePath: deps.getHermesChatFilePath,
    getHermesChatFileRecord: deps.getHermesChatFileRecord,
    getHermesRuntimeState: deps.getHermesRuntimeState,
    hermesAgentDefinition: deps.hermesAgentDefinition,
    openFileInEditor: deps.openFileInEditor,
    parseHermesChatHistoryContent: deps.parseHermesChatHistoryContent,
    persistHermesChatError: deps.persistHermesChatError,
    persistHermesChatFailure: deps.persistHermesChatFailure,
    persistHermesChatPrompt: deps.persistHermesChatPrompt,
    persistHermesChatReply: deps.persistHermesChatReply,
    readHermesChatHistory: deps.readHermesChatHistory,
    readStoredHermesChatHistory: deps.readStoredHermesChatHistory,
    requestJsonWithoutHeadersTimeout: deps.requestJsonWithoutHeadersTimeout,
    setActiveHermesChatRequest: deps.setActiveHermesChatRequest,
    writeHermesChatHistory: deps.writeHermesChatHistory,
  }
}